// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AspnetCoreMvcFull.DB
{
    public partial class Calificaciones
    {
      [Key]
      [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdCalificacion { get; set; }
        public int IdInscripcion { get; set; }
        public decimal? Nota { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual Inscripciones IdInscripcionNavigation { get; set; }
    }
}
