// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AspnetCoreMvcFull.DB
{
    public partial class ColegioContext : IdentityDbContext<IdentityUser, IdentityRole, string>
  {
        public ColegioContext()
        {
        }

        public ColegioContext(DbContextOptions<ColegioContext> options): base(options)
        {
        }

        public virtual DbSet<Aulas> Aulas { get; set; }
        public virtual DbSet<Calificaciones> Calificaciones { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Inscripciones> Inscripciones { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Aulas>(entity =>
            {
                entity.HasKey(e => e.IdAula)
                    .HasName("PK__Aulas__2C89573C52BC6EBD");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(55)
                    .IsUnicode(false);
            });
      
            modelBuilder.Entity<Calificaciones>(entity =>
            {
                entity.HasKey(e => e.IdCalificacion)
                    .HasName("PK__Califica__40E4A751C677E11A");

                entity.Property(e => e.FechaRegistro)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Nota).HasColumnType("decimal(5, 2)");

                entity.HasOne(d => d.IdInscripcionNavigation)
                    .WithMany(p => p.Calificaciones)
                    .HasForeignKey(d => d.IdInscripcion)
                    .HasConstraintName("FK__Calificac__IdIns__38996AB5");
            });

            modelBuilder.Entity<Estudiantes>(entity =>
            {
                entity.HasKey(e => e.IdEstudiante)
                    .HasName("PK__Estudian__B5007C2471A039EA");

                entity.HasIndex(e => e.Email, "UQ__Estudian__A9D10534F2B32C2A")
                    .IsUnique();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Direccion)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.FechaNacimiento).HasColumnType("date");

                entity.Property(e => e.Genero)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Telefono)
                    .HasMaxLength(15)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Inscripciones>(entity =>
            {
                entity.HasKey(e => e.IdInscripcion)
                    .HasName("PK__Inscripc__A122F2BFD868C026");

                entity.Property(e => e.FechaInscripcion)
                    .HasColumnType("date")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.IdEstudianteNavigation)
                    .WithMany(p => p.Inscripciones)
                    .HasForeignKey(d => d.IdEstudiante)
                    .HasConstraintName("FK__Inscripci__IdEst__32E0915F");

                entity.HasOne(d => d.IdMateriaNavigation)
                    .WithMany(p => p.Inscripciones)
                    .HasForeignKey(d => d.IdMateria)
                    .HasConstraintName("FK__Inscripci__IdMat__33D4B598");
            });

            modelBuilder.Entity<Materias>(entity =>
            {
                entity.HasKey(e => e.IdMateria)
                    .HasName("PK__Materias__EC17467008F4E13E");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.IdProfesorNavigation)
                    .WithMany(p => p.Materias)
                    .HasForeignKey(d => d.IdProfesor)
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("FK__Materias__IdProf__2C3393D0");
            });

            modelBuilder.Entity<Profesores>(entity =>
            {
                entity.HasKey(e => e.IdProfesor)
                    .HasName("PK__Profesor__C377C3A11605493C");

                entity.HasIndex(e => e.Email, "UQ__Profesor__A9D10534474F0AB1")
                    .IsUnique();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Especialidad)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Telefono)
                    .HasMaxLength(15)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
