// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AspnetCoreMvcFull.DB
{
    public partial class Inscripciones
    {
        public Inscripciones()
        {
            Calificaciones = new HashSet<Calificaciones>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdInscripcion { get; set; }
        public int IdEstudiante { get; set; }
        public int IdMateria { get; set; }
        public DateTime? FechaInscripcion { get; set; }

        public virtual Estudiantes IdEstudianteNavigation { get; set; }
        public virtual Materias IdMateriaNavigation { get; set; }
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
    }
}
