// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AspnetCoreMvcFull.DB
{
    public partial class Materias
    {
        public Materias()
        {
            Inscripciones = new HashSet<Inscripciones>();
        }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdMateria { get; set; }
        public string Nombre { get; set; }
        public int? Creditos { get; set; }
        public int? IdProfesor { get; set; }

        public virtual Profesores IdProfesorNavigation { get; set; }
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }
    }
}
